### ISSUE TITLE
Clarification and Issues Reproducing ToRA-Code-34b Results

### ISSUE THREAD

**Issue by LiuTaowen-Tony** [microsoft/ToRA#21]
## Issue Description
Hello, I am currently working on reproducing the results of ToRA, specifically with the ToRA-Code-34b model, but I am facing some challenges with precision and memory requirements. I would greatly appreciate some clarifications and assistance.

## Reproduction Steps and Challenges
- **Data Distillation**: I distilled approximately 16,000 samples from ToRA-Code-34b by sampling 10 trajectories per question and removing incorrect trajectories.
- **Precision Issue**: Despite following the above approach, the precision of my results does not match the reported results in your documentation. Could there be any specific steps or settings I might be missing?

## Questions Regarding Fine-Tuning and Memory Requirements
1. **DeepSpeed Configuration**: Can you confirm if the DeepSpeed settings used for fine-tuning ToRA-Code-34b are exactly as specified in [this configuration](https://github.com/microsoft/ToRA/blob/main/src/ds_configs/stage3_offload_optim_accelerate.conf)?
2. **Memory Requirements**: How much memory would finetuning 34B model require? I estimate it would require around 1TB of memory, which I only have around 250GB of memory. I therefore used 8bit-optimizer for finetuning. May I ask the machine configuration for training ToRA.

## Clarification on Base Model
- Could you please confirm whether ToRA-Code is fine-tuned on top of CodeLlama-Python or Code-Instruct?

## Questions About Multi-Step Scenarios
- Similar to this comment [ICLR 2024](https://openreview.net/forum?id=Ep0TtjVoap&noteId=cWELmNEqnb) we also observed a lack of multi-step or looping scenarios in the actual data. 

Thank you for your time and assistance in addressing these questions. Your insights will be invaluable in helping me accurately reproduce and understand the ToRA-Code-34b model.

**Comment by ZubinGou** [comment]
Hi,

Thank you for reaching out. Here are clarifications for your queries:

1. **DeepSpeed Configuration:**
   - Yes, we utilized the reference configuration, specifically Zero Stage 3 with optimizer offload.

2. **Memory Requirements:**
   - We trained ToRA-Code-34b on an H100 80G with 8 GPUs. Your available 250GB memory is sufficient. However, instead of using 8bit-optimizer, I suggest using parameter offloading when OOM to maintain performance.

3. **Base Model:**
   - ToRA-Code is fine-tuned from CodeLlama-Python.

4. **Multi-Step Scenarios:**
   - The majority of ToRA-v1's data consists of "rationale -> program -> rationale" or "program -> rationale" sequences, and only a few data contains many loops. Note that this is highly dependent on the GPT-4 prompt used.
   - Early ToRA versions prompted GPT-4 to generate more looping data, but we found that a simple "rationale -> program -> rationale" looping addresses most problems in GSM8k and MATH. We leave more complex looping of "rationale" and "program" for future exploration.

**Comment by LiuTaowen-Tony** [comment]
Thank you for your prompt response! That is very helpful!
